### ISSUE TITLE
OAuth2 - getTokensAuthorizationCodeGrant throw BoxSdkError

### ISSUE THREAD

**Issue by KevinForys** [box/box-typescript-sdk-gen#451]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I have started to migrate a BoxNodeSDK app to the BoxTSSDK.

My app is an Box Web Integration with an OAuth2 Authentication.

When I use the function `await oauth.getTokensAuthorizationCodeGrant('code');`, the Box TS SDK throw :

```
node_modules/box-typescript-sdk-gen/lib/schemas/fileOrFolderScope.generated.js:55
    throw new errors_js_1.BoxSdkError({
          ^
BoxSdkError: Can't deserialize FileOrFolderScopeScopeField
    at deserializeFileOrFolderScopeScopeField (node_modules/box-typescript-sdk-gen/lib/schemas/fileOrFolderScope.generated.js:55:11)
```

### Steps to Reproduce

1. I open my Box Integration App from a Box folder
2. The app start correctly the OAuth2 Authentication process
3. The BoxNodeSDK crashed when I use oauth.getTokensAuthorizationCodeGrant('correct_code');

### Error Message, Including Stack Trace

```
BoxSdkError: Can't deserialize FileOrFolderScopeScopeField
    at deserializeFileOrFolderScopeScopeField (node_modules/box-typescript-sdk-gen/lib/schemas/fileOrFolderScope.generated.js:55:11)
    at deserializeFileOrFolderScope (node_modules/box-typescript-sdk-gen/lib/schemas/fileOrFolderScope.generated.js:77:11)
    at node_modules/box-typescript-sdk-gen/lib/schemas/accessToken.generated.js:84:90
    at Array.map (<anonymous>)
    at deserializeAccessToken node_modules/box-typescript-sdk-gen/lib/schemas/accessToken.generated.js:83:33)
    at AuthorizationManager.<anonymous> (node_modules/box-typescript-sdk-gen/lib/managers/authorization.generated.js:210:106)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/box-typescript-sdk-gen/lib/managers/authorization.generated.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Patch

I have investigate on my side and it's look like that the scope '**item_read**' is missing inside the deserializeFileOrFolderScopeScopeField() loop.

box-typescript-sdk-gen/lib/schemas/fileOrFolderScope.generated.js:55 :
```
export function deserializeFileOrFolderScopeScopeField(
  val: SerializedData,
): FileOrFolderScopeScopeField {
  
  if (val == 'item_read') { // Missing this scope.
    return val;
  }
  if (val == 'annotation_edit') {
    return val;
  }
  if (val == 'annotation_view_all') {
    return val;
  }
  if (val == 'annotation_view_self') {
    return val;
  }
  if (val == 'base_explorer') {
    return val;
  }
  if (val == 'base_picker') {
    return val;
  }
  if (val == 'base_preview') {
    return val;
  }
  if (val == 'base_upload') {
    return val;
  }
  if (val == 'item_delete') {
    return val;
  }
  if (val == 'item_download') {
    return val;
  }
  if (val == 'item_preview') {
    return val;
  }
  if (val == 'item_rename') {
    return val;
  }
  if (val == 'item_share') {
    return val;
  }
  if (val == 'item_upload') {
    return val;
  }
  throw new BoxSdkError({
    message: "Can't deserialize FileOrFolderScopeScopeField",
  });
}
```

### Versions Used

Typescript SDK: v1.9.0
Platform: Node.js
Node.js : v20.18.1

**Comment by mwwoda** [comment]
Hello,
Looks like the scope you are receiving is missing from the spec https://developer.box.com/reference/resources/access-token/#param-restricted_to-scope. This SDK is generated based on spec and currently it's very strict about deserializing enum values from API - if value not present on the list of possible values is present it usually throws exception. We plan change this to allow any custom values during deserialization. I'll will also check what we could do from the spec side.

**Comment by mwwoda** [comment]
It was fixed in the spec and we have a pedning PR in this repo reflecting the change https://github.com/box/box-typescript-sdk-gen/pull/459

**Comment by KevinForys** [comment]
Thanks for the faster update.

I see that the PR is merged into _main_, how can I test this fix?

I tried to install directly the main branch like that :

` npm install "https://github.com/box/box-typescript-sdk-gen#main" --save `

But this error is thrown in my project :

```
node:internal/modules/cjs/loader:1228
  throw err;
  ^
Error: Cannot find module 'box-typescript-sdk-gen/lib/box/oauth.generated.js'
```

**Comment by congminh1254** [comment]
Hi @KevinForys 

We have just released new version of Box TS SDK, please take a look.
